<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://wsbanque.service.mylogos.top" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="BanqueServiceImplService" targetNamespace="http://wsbanque.service.mylogos.top">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://wsbanque.service.mylogos.top" elementFormDefault="unqualified" targetNamespace="http://wsbanque.service.mylogos.top" version="1.0">

  <xs:element name="payer" type="tns:payer"/>

  <xs:element name="payerResponse" type="tns:payerResponse"/>

  <xs:complexType name="payer">
    <xs:sequence>
      <xs:element minOccurs="0" name="paiement" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="payerResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="retourPaiement" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="payerResponse">
    <wsdl:part element="tns:payerResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="payer">
    <wsdl:part element="tns:payer" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="BanqueService">
    <wsdl:operation name="payer">
      <wsdl:input message="tns:payer" name="payer">
    </wsdl:input>
      <wsdl:output message="tns:payerResponse" name="payerResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BanqueServiceImplServiceSoapBinding" type="tns:BanqueService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="payer">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="payer">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="payerResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BanqueServiceImplService">
    <wsdl:port binding="tns:BanqueServiceImplServiceSoapBinding" name="BanqueServiceImplPort">
      <soap:address location="http://localhost:8080/Banque/banque"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>